// Code generated by protoc-gen-go. DO NOT EDIT.
// source: obj.proto

package protoobj

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 媒体平台，uc，qq快报等
type MediaType int32

const (
	MediaType_Null MediaType = 0
)

var MediaType_name = map[int32]string{
	0: "Null",
}
var MediaType_value = map[string]int32{
	"Null": 0,
}

func (x MediaType) String() string {
	return proto.EnumName(MediaType_name, int32(x))
}
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_obj_2f3f6e5f61eb27b5, []int{0}
}

type StatusCode int32

const (
	// 空闲，未开始
	StatusCode_IDLE StatusCode = 0
	// 等待，队列中等待
	StatusCode_Waiting  StatusCode = 1
	StatusCode_Running  StatusCode = 2
	StatusCode_Finished StatusCode = 3
)

var StatusCode_name = map[int32]string{
	0: "IDLE",
	1: "Waiting",
	2: "Running",
	3: "Finished",
}
var StatusCode_value = map[string]int32{
	"IDLE":     0,
	"Waiting":  1,
	"Running":  2,
	"Finished": 3,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_obj_2f3f6e5f61eb27b5, []int{1}
}

type ArticleObj struct {
	Dbid int64 `protobuf:"varint,1,opt,name=dbid,proto3" json:"dbid,omitempty"`
	// 在各个平台的id，用于判断文章是否重复
	Idstr      string `protobuf:"bytes,2,opt,name=idstr,proto3" json:"idstr,omitempty"`
	Title      string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	SourceData string `protobuf:"bytes,4,opt,name=sourceData,proto3" json:"sourceData,omitempty"`
	Content    string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	// 文章页链接
	Weburl string `protobuf:"bytes,6,opt,name=weburl,proto3" json:"weburl,omitempty"`
	// 发布时间，UTC秒
	PublishUnix int64 `protobuf:"varint,7,opt,name=publishUnix,proto3" json:"publishUnix,omitempty"`
	// 开始采集此文的时间 UTC秒
	CreatedUnix int64     `protobuf:"varint,8,opt,name=createdUnix,proto3" json:"createdUnix,omitempty"`
	MediaType   MediaType `protobuf:"varint,10,opt,name=mediaType,proto3,enum=protoobj.MediaType" json:"mediaType,omitempty"`
	// 作者数据
	Author *UserObj `protobuf:"bytes,11,opt,name=author,proto3" json:"author,omitempty"`
	// 公众号数据
	Account *AccountObj `protobuf:"bytes,12,opt,name=account,proto3" json:"account,omitempty"`
	// 所属任务
	CrawlerTaskObj *CrawlerTaskObj `protobuf:"bytes,13,opt,name=crawlerTaskObj,proto3" json:"crawlerTaskObj,omitempty"`
	Video          *VideoObj       `protobuf:"bytes,14,opt,name=video,proto3" json:"video,omitempty"`
	ReadCount      int32           `protobuf:"varint,20,opt,name=readCount,proto3" json:"readCount,omitempty"`
	CommentCount   int32           `protobuf:"varint,21,opt,name=commentCount,proto3" json:"commentCount,omitempty"`
	StatusCode     StatusCode      `protobuf:"varint,22,opt,name=statusCode,proto3,enum=protoobj.StatusCode" json:"statusCode,omitempty"`
	// 其它数据
	Data                 map[string]*any.Any `protobuf:"bytes,23,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ArticleObj) Reset()         { *m = ArticleObj{} }
func (m *ArticleObj) String() string { return proto.CompactTextString(m) }
func (*ArticleObj) ProtoMessage()    {}
func (*ArticleObj) Descriptor() ([]byte, []int) {
	return fileDescriptor_obj_2f3f6e5f61eb27b5, []int{0}
}
func (m *ArticleObj) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleObj.Unmarshal(m, b)
}
func (m *ArticleObj) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleObj.Marshal(b, m, deterministic)
}
func (dst *ArticleObj) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleObj.Merge(dst, src)
}
func (m *ArticleObj) XXX_Size() int {
	return xxx_messageInfo_ArticleObj.Size(m)
}
func (m *ArticleObj) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleObj.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleObj proto.InternalMessageInfo

func (m *ArticleObj) GetDbid() int64 {
	if m != nil {
		return m.Dbid
	}
	return 0
}

func (m *ArticleObj) GetIdstr() string {
	if m != nil {
		return m.Idstr
	}
	return ""
}

func (m *ArticleObj) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ArticleObj) GetSourceData() string {
	if m != nil {
		return m.SourceData
	}
	return ""
}

func (m *ArticleObj) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ArticleObj) GetWeburl() string {
	if m != nil {
		return m.Weburl
	}
	return ""
}

func (m *ArticleObj) GetPublishUnix() int64 {
	if m != nil {
		return m.PublishUnix
	}
	return 0
}

func (m *ArticleObj) GetCreatedUnix() int64 {
	if m != nil {
		return m.CreatedUnix
	}
	return 0
}

func (m *ArticleObj) GetMediaType() MediaType {
	if m != nil {
		return m.MediaType
	}
	return MediaType_Null
}

func (m *ArticleObj) GetAuthor() *UserObj {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *ArticleObj) GetAccount() *AccountObj {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *ArticleObj) GetCrawlerTaskObj() *CrawlerTaskObj {
	if m != nil {
		return m.CrawlerTaskObj
	}
	return nil
}

func (m *ArticleObj) GetVideo() *VideoObj {
	if m != nil {
		return m.Video
	}
	return nil
}

func (m *ArticleObj) GetReadCount() int32 {
	if m != nil {
		return m.ReadCount
	}
	return 0
}

func (m *ArticleObj) GetCommentCount() int32 {
	if m != nil {
		return m.CommentCount
	}
	return 0
}

func (m *ArticleObj) GetStatusCode() StatusCode {
	if m != nil {
		return m.StatusCode
	}
	return StatusCode_IDLE
}

func (m *ArticleObj) GetData() map[string]*any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

// 视频类数据
type VideoObj struct {
	Idstr string `protobuf:"bytes,1,opt,name=idstr,proto3" json:"idstr,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// 视频播放地址
	PlayUrl string `protobuf:"bytes,3,opt,name=playUrl,proto3" json:"playUrl,omitempty"`
	// 其它数据
	Data                 map[string]*any.Any `protobuf:"bytes,20,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *VideoObj) Reset()         { *m = VideoObj{} }
func (m *VideoObj) String() string { return proto.CompactTextString(m) }
func (*VideoObj) ProtoMessage()    {}
func (*VideoObj) Descriptor() ([]byte, []int) {
	return fileDescriptor_obj_2f3f6e5f61eb27b5, []int{1}
}
func (m *VideoObj) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoObj.Unmarshal(m, b)
}
func (m *VideoObj) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoObj.Marshal(b, m, deterministic)
}
func (dst *VideoObj) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoObj.Merge(dst, src)
}
func (m *VideoObj) XXX_Size() int {
	return xxx_messageInfo_VideoObj.Size(m)
}
func (m *VideoObj) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoObj.DiscardUnknown(m)
}

var xxx_messageInfo_VideoObj proto.InternalMessageInfo

func (m *VideoObj) GetIdstr() string {
	if m != nil {
		return m.Idstr
	}
	return ""
}

func (m *VideoObj) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *VideoObj) GetPlayUrl() string {
	if m != nil {
		return m.PlayUrl
	}
	return ""
}

func (m *VideoObj) GetData() map[string]*any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserObj struct {
	Dbid int64 `protobuf:"varint,1,opt,name=dbid,proto3" json:"dbid,omitempty"`
	// 平台id,或唯一帐号
	Idstr    string `protobuf:"bytes,2,opt,name=idstr,proto3" json:"idstr,omitempty"`
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 头像
	AvatarUrl string `protobuf:"bytes,4,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
	// 主页链接
	HomepageUrl string `protobuf:"bytes,5,opt,name=homepageUrl,proto3" json:"homepageUrl,omitempty"`
	// 描述介绍
	Desc      string    `protobuf:"bytes,6,opt,name=desc,proto3" json:"desc,omitempty"`
	MediaType MediaType `protobuf:"varint,7,opt,name=mediaType,proto3,enum=protoobj.MediaType" json:"mediaType,omitempty"`
	// 创建此用户时间 UTC秒
	CreatedUnix int64 `protobuf:"varint,20,opt,name=createdUnix,proto3" json:"createdUnix,omitempty"`
	// 其它数据
	Data                 map[string]*any.Any `protobuf:"bytes,21,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UserObj) Reset()         { *m = UserObj{} }
func (m *UserObj) String() string { return proto.CompactTextString(m) }
func (*UserObj) ProtoMessage()    {}
func (*UserObj) Descriptor() ([]byte, []int) {
	return fileDescriptor_obj_2f3f6e5f61eb27b5, []int{2}
}
func (m *UserObj) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserObj.Unmarshal(m, b)
}
func (m *UserObj) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserObj.Marshal(b, m, deterministic)
}
func (dst *UserObj) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserObj.Merge(dst, src)
}
func (m *UserObj) XXX_Size() int {
	return xxx_messageInfo_UserObj.Size(m)
}
func (m *UserObj) XXX_DiscardUnknown() {
	xxx_messageInfo_UserObj.DiscardUnknown(m)
}

var xxx_messageInfo_UserObj proto.InternalMessageInfo

func (m *UserObj) GetDbid() int64 {
	if m != nil {
		return m.Dbid
	}
	return 0
}

func (m *UserObj) GetIdstr() string {
	if m != nil {
		return m.Idstr
	}
	return ""
}

func (m *UserObj) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserObj) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *UserObj) GetHomepageUrl() string {
	if m != nil {
		return m.HomepageUrl
	}
	return ""
}

func (m *UserObj) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *UserObj) GetMediaType() MediaType {
	if m != nil {
		return m.MediaType
	}
	return MediaType_Null
}

func (m *UserObj) GetCreatedUnix() int64 {
	if m != nil {
		return m.CreatedUnix
	}
	return 0
}

func (m *UserObj) GetData() map[string]*any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

// 媒体帐号
type AccountObj struct {
	Dbid int64 `protobuf:"varint,1,opt,name=dbid,proto3" json:"dbid,omitempty"`
	// 平台id
	Idstr string `protobuf:"bytes,2,opt,name=idstr,proto3" json:"idstr,omitempty"`
	// 帐号名
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// 简介描述
	Desc string `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	// 主页
	HomepageUrl string `protobuf:"bytes,5,opt,name=homepageUrl,proto3" json:"homepageUrl,omitempty"`
	// 帐号头像
	AvatarUrl string    `protobuf:"bytes,6,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
	MediaType MediaType `protobuf:"varint,7,opt,name=mediaType,proto3,enum=protoobj.MediaType" json:"mediaType,omitempty"`
	// 创建此媒体号时间/入库时间 UTC秒
	CreatedUnix int64 `protobuf:"varint,20,opt,name=createdUnix,proto3" json:"createdUnix,omitempty"`
	// 其它数据
	Data                 map[string]*any.Any `protobuf:"bytes,21,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AccountObj) Reset()         { *m = AccountObj{} }
func (m *AccountObj) String() string { return proto.CompactTextString(m) }
func (*AccountObj) ProtoMessage()    {}
func (*AccountObj) Descriptor() ([]byte, []int) {
	return fileDescriptor_obj_2f3f6e5f61eb27b5, []int{3}
}
func (m *AccountObj) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountObj.Unmarshal(m, b)
}
func (m *AccountObj) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountObj.Marshal(b, m, deterministic)
}
func (dst *AccountObj) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountObj.Merge(dst, src)
}
func (m *AccountObj) XXX_Size() int {
	return xxx_messageInfo_AccountObj.Size(m)
}
func (m *AccountObj) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountObj.DiscardUnknown(m)
}

var xxx_messageInfo_AccountObj proto.InternalMessageInfo

func (m *AccountObj) GetDbid() int64 {
	if m != nil {
		return m.Dbid
	}
	return 0
}

func (m *AccountObj) GetIdstr() string {
	if m != nil {
		return m.Idstr
	}
	return ""
}

func (m *AccountObj) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AccountObj) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *AccountObj) GetHomepageUrl() string {
	if m != nil {
		return m.HomepageUrl
	}
	return ""
}

func (m *AccountObj) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *AccountObj) GetMediaType() MediaType {
	if m != nil {
		return m.MediaType
	}
	return MediaType_Null
}

func (m *AccountObj) GetCreatedUnix() int64 {
	if m != nil {
		return m.CreatedUnix
	}
	return 0
}

func (m *AccountObj) GetData() map[string]*any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

// 采集任务
type CrawlerTaskObj struct {
	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 起始采集页
	IndexUrl string `protobuf:"bytes,3,opt,name=indexUrl,proto3" json:"indexUrl,omitempty"`
	// 任务当前状态
	StatusCode StatusCode `protobuf:"varint,4,opt,name=statusCode,proto3,enum=protoobj.StatusCode" json:"statusCode,omitempty"`
	// 任务开始时 时间 UTC秒
	StartUnix int64 `protobuf:"varint,20,opt,name=startUnix,proto3" json:"startUnix,omitempty"`
	// 任务结束时，时间 UTC秒
	EndUnix              int64    `protobuf:"varint,21,opt,name=endUnix,proto3" json:"endUnix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrawlerTaskObj) Reset()         { *m = CrawlerTaskObj{} }
func (m *CrawlerTaskObj) String() string { return proto.CompactTextString(m) }
func (*CrawlerTaskObj) ProtoMessage()    {}
func (*CrawlerTaskObj) Descriptor() ([]byte, []int) {
	return fileDescriptor_obj_2f3f6e5f61eb27b5, []int{4}
}
func (m *CrawlerTaskObj) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrawlerTaskObj.Unmarshal(m, b)
}
func (m *CrawlerTaskObj) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrawlerTaskObj.Marshal(b, m, deterministic)
}
func (dst *CrawlerTaskObj) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrawlerTaskObj.Merge(dst, src)
}
func (m *CrawlerTaskObj) XXX_Size() int {
	return xxx_messageInfo_CrawlerTaskObj.Size(m)
}
func (m *CrawlerTaskObj) XXX_DiscardUnknown() {
	xxx_messageInfo_CrawlerTaskObj.DiscardUnknown(m)
}

var xxx_messageInfo_CrawlerTaskObj proto.InternalMessageInfo

func (m *CrawlerTaskObj) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CrawlerTaskObj) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CrawlerTaskObj) GetIndexUrl() string {
	if m != nil {
		return m.IndexUrl
	}
	return ""
}

func (m *CrawlerTaskObj) GetStatusCode() StatusCode {
	if m != nil {
		return m.StatusCode
	}
	return StatusCode_IDLE
}

func (m *CrawlerTaskObj) GetStartUnix() int64 {
	if m != nil {
		return m.StartUnix
	}
	return 0
}

func (m *CrawlerTaskObj) GetEndUnix() int64 {
	if m != nil {
		return m.EndUnix
	}
	return 0
}

func init() {
	proto.RegisterType((*ArticleObj)(nil), "protoobj.ArticleObj")
	proto.RegisterMapType((map[string]*any.Any)(nil), "protoobj.ArticleObj.DataEntry")
	proto.RegisterType((*VideoObj)(nil), "protoobj.VideoObj")
	proto.RegisterMapType((map[string]*any.Any)(nil), "protoobj.VideoObj.DataEntry")
	proto.RegisterType((*UserObj)(nil), "protoobj.UserObj")
	proto.RegisterMapType((map[string]*any.Any)(nil), "protoobj.UserObj.DataEntry")
	proto.RegisterType((*AccountObj)(nil), "protoobj.AccountObj")
	proto.RegisterMapType((map[string]*any.Any)(nil), "protoobj.AccountObj.DataEntry")
	proto.RegisterType((*CrawlerTaskObj)(nil), "protoobj.CrawlerTaskObj")
	proto.RegisterEnum("protoobj.MediaType", MediaType_name, MediaType_value)
	proto.RegisterEnum("protoobj.StatusCode", StatusCode_name, StatusCode_value)
}

func init() { proto.RegisterFile("obj.proto", fileDescriptor_obj_2f3f6e5f61eb27b5) }

var fileDescriptor_obj_2f3f6e5f61eb27b5 = []byte{
	// 729 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xcf, 0x6e, 0x13, 0x3b,
	0x14, 0xc6, 0x3b, 0x93, 0xbf, 0x73, 0xd2, 0x1b, 0xe5, 0xfa, 0x26, 0xbd, 0x26, 0x54, 0x55, 0xd4,
	0x55, 0xe8, 0x22, 0x85, 0xc0, 0x02, 0xb1, 0x40, 0x54, 0x6d, 0x91, 0x90, 0x28, 0x95, 0x86, 0x16,
	0xd6, 0x9e, 0x19, 0x93, 0x38, 0x9d, 0xd8, 0x91, 0xc7, 0xd3, 0x36, 0x2f, 0xc7, 0x3b, 0xb0, 0xe2,
	0x4d, 0x10, 0x4b, 0x64, 0xcf, 0xdf, 0xa4, 0x95, 0x68, 0x17, 0x59, 0xc5, 0xe7, 0x3b, 0x9f, 0x15,
	0xfb, 0x37, 0xe7, 0x33, 0x38, 0xc2, 0x9b, 0x8d, 0x16, 0x52, 0x28, 0x81, 0x9a, 0xe6, 0x47, 0x78,
	0xb3, 0xfe, 0x93, 0x89, 0x10, 0x93, 0x90, 0x1e, 0x1a, 0xc1, 0x8b, 0xbf, 0x1d, 0x12, 0xbe, 0x4c,
	0x4c, 0xfb, 0x3f, 0x6b, 0x00, 0x47, 0x52, 0x31, 0x3f, 0xa4, 0xe7, 0xde, 0x0c, 0x21, 0xa8, 0x06,
	0x1e, 0x0b, 0xb0, 0x35, 0xb0, 0x86, 0x15, 0xd7, 0xac, 0x51, 0x17, 0x6a, 0x2c, 0x88, 0x94, 0xc4,
	0xf6, 0xc0, 0x1a, 0x3a, 0x6e, 0x52, 0x68, 0x55, 0x31, 0x15, 0x52, 0x5c, 0x49, 0x54, 0x53, 0xa0,
	0x3d, 0x80, 0x48, 0xc4, 0xd2, 0xa7, 0x27, 0x44, 0x11, 0x5c, 0x35, 0xad, 0x92, 0x82, 0x30, 0x34,
	0x7c, 0xc1, 0x15, 0xe5, 0x0a, 0xd7, 0x4c, 0x33, 0x2b, 0xd1, 0x0e, 0xd4, 0x6f, 0xa8, 0x17, 0xcb,
	0x10, 0xd7, 0x4d, 0x23, 0xad, 0xd0, 0x00, 0x5a, 0x8b, 0xd8, 0x0b, 0x59, 0x34, 0xbd, 0xe4, 0xec,
	0x16, 0x37, 0xcc, 0xc1, 0xca, 0x92, 0x76, 0xf8, 0x92, 0x12, 0x45, 0x03, 0xe3, 0x68, 0x26, 0x8e,
	0x92, 0x84, 0x5e, 0x80, 0x33, 0xa7, 0x01, 0x23, 0x17, 0xcb, 0x05, 0xc5, 0x30, 0xb0, 0x86, 0xed,
	0xf1, 0x7f, 0xa3, 0x8c, 0xce, 0xe8, 0x2c, 0x6b, 0xb9, 0x85, 0x0b, 0x3d, 0x83, 0x3a, 0x89, 0xd5,
	0x54, 0x48, 0xdc, 0x1a, 0x58, 0xc3, 0xd6, 0xf8, 0xdf, 0xc2, 0x7f, 0x19, 0x51, 0x79, 0xee, 0xcd,
	0xdc, 0xd4, 0x80, 0x46, 0xd0, 0x20, 0xbe, 0x2f, 0x62, 0xae, 0xf0, 0xb6, 0xf1, 0x76, 0x0b, 0xef,
	0x51, 0xd2, 0xd0, 0xf6, 0xcc, 0x84, 0xde, 0x41, 0xdb, 0x97, 0xe4, 0x26, 0xa4, 0xf2, 0x82, 0x44,
	0x57, 0xe7, 0xde, 0x0c, 0xff, 0x63, 0xb6, 0xe1, 0x62, 0xdb, 0xf1, 0x4a, 0xdf, 0x5d, 0xf3, 0xa3,
	0x21, 0xd4, 0xae, 0x59, 0x40, 0x05, 0x6e, 0x9b, 0x8d, 0xa8, 0xd8, 0xf8, 0x45, 0xcb, 0x7a, 0x4b,
	0x62, 0x40, 0xbb, 0xe0, 0x48, 0x4a, 0x82, 0x63, 0x73, 0xba, 0xee, 0xc0, 0x1a, 0xd6, 0xdc, 0x42,
	0x40, 0xfb, 0xb0, 0xed, 0x8b, 0xf9, 0x9c, 0x72, 0x95, 0x18, 0x7a, 0xc6, 0xb0, 0xa2, 0xa1, 0x57,
	0x00, 0x91, 0x22, 0x2a, 0x8e, 0x8e, 0x45, 0x40, 0xf1, 0x8e, 0x81, 0x57, 0xba, 0xe0, 0xe7, 0xbc,
	0xe7, 0x96, 0x7c, 0x68, 0x0c, 0xd5, 0x40, 0x4f, 0xc0, 0xff, 0x83, 0xca, 0xb0, 0x35, 0xde, 0x2b,
	0x01, 0xc9, 0x67, 0x6d, 0xa4, 0x07, 0xe2, 0x94, 0x2b, 0xb9, 0x74, 0x8d, 0xb7, 0x7f, 0x06, 0x4e,
	0x2e, 0xa1, 0x0e, 0x54, 0xae, 0xe8, 0xd2, 0xcc, 0xa1, 0xe3, 0xea, 0x25, 0x3a, 0x80, 0xda, 0x35,
	0x09, 0x63, 0x6a, 0xc6, 0x50, 0x43, 0x4e, 0x86, 0x7a, 0x94, 0x0d, 0xf5, 0xe8, 0x88, 0x2f, 0xdd,
	0xc4, 0xf2, 0xc6, 0x7e, 0x6d, 0xed, 0xff, 0xb0, 0xa0, 0x99, 0xe1, 0x28, 0x66, 0xd8, 0xba, 0x77,
	0x86, 0xed, 0xf2, 0x0c, 0x63, 0x68, 0x2c, 0x42, 0xb2, 0xbc, 0x94, 0x61, 0x3a, 0xdb, 0x59, 0x89,
	0x9e, 0xa7, 0xb7, 0xea, 0x9a, 0x5b, 0xed, 0xde, 0xc5, 0xbe, 0xe9, 0x3b, 0xfd, 0xb6, 0xa1, 0x91,
	0x8e, 0xdf, 0x23, 0xa2, 0xda, 0x87, 0x26, 0x67, 0xfe, 0x15, 0x27, 0xf3, 0x2c, 0xad, 0x79, 0xad,
	0x07, 0x84, 0x5c, 0x13, 0x45, 0xa4, 0xbe, 0x6e, 0x92, 0xd7, 0x42, 0xd0, 0xd1, 0x9a, 0x8a, 0x39,
	0x5d, 0x90, 0x09, 0xd5, 0xfd, 0x24, 0xb2, 0x65, 0xc9, 0x9c, 0x82, 0x46, 0x7e, 0x1a, 0x5a, 0xb3,
	0x5e, 0x8d, 0x5b, 0xe3, 0x41, 0x71, 0x5b, 0xcb, 0x70, 0xf7, 0x6e, 0x86, 0x0f, 0x53, 0xf6, 0x3d,
	0xc3, 0xfe, 0xe9, 0x9d, 0x38, 0x6e, 0x1a, 0xfd, 0x2f, 0x1b, 0xa0, 0x48, 0xf3, 0x23, 0xe8, 0x23,
	0xa8, 0x96, 0xc8, 0x9b, 0x75, 0x4e, 0xad, 0x5a, 0xa2, 0xf6, 0x77, 0xd6, 0x2b, 0xdf, 0xaa, 0xbe,
	0xfe, 0xad, 0x36, 0x42, 0x7d, 0xbc, 0x42, 0x7d, 0xef, 0xbe, 0x87, 0x6d, 0xd3, 0xe0, 0xbf, 0x5b,
	0xd0, 0x5e, 0x7d, 0x0f, 0x51, 0x1b, 0xec, 0x1c, 0xbd, 0xcd, 0x82, 0x1c, 0xb1, 0x5d, 0x42, 0xdc,
	0x87, 0x26, 0xe3, 0x01, 0xbd, 0x2d, 0x62, 0x9c, 0xd7, 0x6b, 0x6f, 0x5a, 0xf5, 0x81, 0x6f, 0xda,
	0x2e, 0x38, 0x91, 0x22, 0x52, 0x95, 0x58, 0x15, 0x82, 0x7e, 0x35, 0x28, 0x4f, 0x38, 0xf6, 0x4c,
	0x2f, 0x2b, 0x0f, 0x7a, 0xe0, 0xe4, 0xf4, 0x51, 0x13, 0xaa, 0x9f, 0xe2, 0x30, 0xec, 0x6c, 0x1d,
	0xbc, 0x05, 0x28, 0xfe, 0x48, 0xeb, 0x1f, 0x4e, 0x3e, 0x9e, 0x76, 0xb6, 0x50, 0x0b, 0x1a, 0x5f,
	0x09, 0x53, 0x8c, 0x4f, 0x3a, 0x96, 0x2e, 0xdc, 0x98, 0x73, 0x5d, 0xd8, 0x68, 0x1b, 0x9a, 0xef,
	0x19, 0x67, 0xd1, 0x94, 0x06, 0x9d, 0x8a, 0x57, 0x37, 0xe7, 0x7d, 0xf9, 0x27, 0x00, 0x00, 0xff,
	0xff, 0x98, 0x8a, 0xbe, 0x91, 0xf2, 0x07, 0x00, 0x00,
}
