// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/crawler.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/crawler.proto

It has these top-level messages:
	ArticleObj
	UserObj
	MediaObj
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type ArticleObj struct {
	Dbid           int64                           `protobuf:"zigzag64,1,opt,name=dbid" json:"dbid,omitempty"`
	SourceId       string                          `protobuf:"bytes,2,opt,name=sourceId" json:"sourceId,omitempty"`
	Title          string                          `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	ContentHtml    string                          `protobuf:"bytes,4,opt,name=contentHtml" json:"contentHtml,omitempty"`
	Author         *UserObj                        `protobuf:"bytes,5,opt,name=author" json:"author,omitempty"`
	SourceSiteName string                          `protobuf:"bytes,6,opt,name=sourceSiteName" json:"sourceSiteName,omitempty"`
	SourcePubUTC   int64                           `protobuf:"zigzag64,7,opt,name=SourcePubUTC" json:"SourcePubUTC,omitempty"`
	SourcePubTime  string                          `protobuf:"bytes,8,opt,name=SourcePubTime" json:"SourcePubTime,omitempty"`
	SourceUrl      string                          `protobuf:"bytes,9,opt,name=sourceUrl" json:"sourceUrl,omitempty"`
	ThumbnailsUrl  []string                        `protobuf:"bytes,10,rep,name=thumbnailsUrl" json:"thumbnailsUrl,omitempty"`
	Media          *MediaObj                       `protobuf:"bytes,11,opt,name=media" json:"media,omitempty"`
	SourceSiteCode string                          `protobuf:"bytes,12,opt,name=sourceSiteCode" json:"sourceSiteCode,omitempty"`
	LikeNum        int64                           `protobuf:"zigzag64,20,opt,name=likeNum" json:"likeNum,omitempty"`
	CommentNum     int64                           `protobuf:"zigzag64,21,opt,name=commentNum" json:"commentNum,omitempty"`
	ReadNum        int64                           `protobuf:"zigzag64,22,opt,name=readNum" json:"readNum,omitempty"`
	CreateUTC      int64                           `protobuf:"zigzag64,23,opt,name=createUTC" json:"createUTC,omitempty"`
	CreateTime     string                          `protobuf:"bytes,24,opt,name=createTime" json:"createTime,omitempty"`
	OtherData      map[string]*google_protobuf.Any `protobuf:"bytes,30,rep,name=otherData" json:"otherData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ArticleObj) Reset()                    { *m = ArticleObj{} }
func (m *ArticleObj) String() string            { return proto1.CompactTextString(m) }
func (*ArticleObj) ProtoMessage()               {}
func (*ArticleObj) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ArticleObj) GetDbid() int64 {
	if m != nil {
		return m.Dbid
	}
	return 0
}

func (m *ArticleObj) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

func (m *ArticleObj) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ArticleObj) GetContentHtml() string {
	if m != nil {
		return m.ContentHtml
	}
	return ""
}

func (m *ArticleObj) GetAuthor() *UserObj {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *ArticleObj) GetSourceSiteName() string {
	if m != nil {
		return m.SourceSiteName
	}
	return ""
}

func (m *ArticleObj) GetSourcePubUTC() int64 {
	if m != nil {
		return m.SourcePubUTC
	}
	return 0
}

func (m *ArticleObj) GetSourcePubTime() string {
	if m != nil {
		return m.SourcePubTime
	}
	return ""
}

func (m *ArticleObj) GetSourceUrl() string {
	if m != nil {
		return m.SourceUrl
	}
	return ""
}

func (m *ArticleObj) GetThumbnailsUrl() []string {
	if m != nil {
		return m.ThumbnailsUrl
	}
	return nil
}

func (m *ArticleObj) GetMedia() *MediaObj {
	if m != nil {
		return m.Media
	}
	return nil
}

func (m *ArticleObj) GetSourceSiteCode() string {
	if m != nil {
		return m.SourceSiteCode
	}
	return ""
}

func (m *ArticleObj) GetLikeNum() int64 {
	if m != nil {
		return m.LikeNum
	}
	return 0
}

func (m *ArticleObj) GetCommentNum() int64 {
	if m != nil {
		return m.CommentNum
	}
	return 0
}

func (m *ArticleObj) GetReadNum() int64 {
	if m != nil {
		return m.ReadNum
	}
	return 0
}

func (m *ArticleObj) GetCreateUTC() int64 {
	if m != nil {
		return m.CreateUTC
	}
	return 0
}

func (m *ArticleObj) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *ArticleObj) GetOtherData() map[string]*google_protobuf.Any {
	if m != nil {
		return m.OtherData
	}
	return nil
}

type UserObj struct {
	Dbid           int64                           `protobuf:"zigzag64,1,opt,name=dbid" json:"dbid,omitempty"`
	SourceId       string                          `protobuf:"bytes,2,opt,name=sourceId" json:"sourceId,omitempty"`
	Nickname       string                          `protobuf:"bytes,3,opt,name=nickname" json:"nickname,omitempty"`
	IconUrl        string                          `protobuf:"bytes,4,opt,name=iconUrl" json:"iconUrl,omitempty"`
	AccountNum     string                          `protobuf:"bytes,5,opt,name=accountNum" json:"accountNum,omitempty"`
	SourceSiteName string                          `protobuf:"bytes,6,opt,name=sourceSiteName" json:"sourceSiteName,omitempty"`
	HomeUrl        string                          `protobuf:"bytes,7,opt,name=homeUrl" json:"homeUrl,omitempty"`
	Des            string                          `protobuf:"bytes,8,opt,name=des" json:"des,omitempty"`
	OtherData      map[string]*google_protobuf.Any `protobuf:"bytes,30,rep,name=otherData" json:"otherData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *UserObj) Reset()                    { *m = UserObj{} }
func (m *UserObj) String() string            { return proto1.CompactTextString(m) }
func (*UserObj) ProtoMessage()               {}
func (*UserObj) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserObj) GetDbid() int64 {
	if m != nil {
		return m.Dbid
	}
	return 0
}

func (m *UserObj) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

func (m *UserObj) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserObj) GetIconUrl() string {
	if m != nil {
		return m.IconUrl
	}
	return ""
}

func (m *UserObj) GetAccountNum() string {
	if m != nil {
		return m.AccountNum
	}
	return ""
}

func (m *UserObj) GetSourceSiteName() string {
	if m != nil {
		return m.SourceSiteName
	}
	return ""
}

func (m *UserObj) GetHomeUrl() string {
	if m != nil {
		return m.HomeUrl
	}
	return ""
}

func (m *UserObj) GetDes() string {
	if m != nil {
		return m.Des
	}
	return ""
}

func (m *UserObj) GetOtherData() map[string]*google_protobuf.Any {
	if m != nil {
		return m.OtherData
	}
	return nil
}

type MediaObj struct {
	SourceId     string                          `protobuf:"bytes,1,opt,name=sourceId" json:"sourceId,omitempty"`
	VideoSrc     string                          `protobuf:"bytes,2,opt,name=videoSrc" json:"videoSrc,omitempty"`
	VideoHtmlUrl string                          `protobuf:"bytes,3,opt,name=videoHtmlUrl" json:"videoHtmlUrl,omitempty"`
	OtherData    map[string]*google_protobuf.Any `protobuf:"bytes,30,rep,name=otherData" json:"otherData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *MediaObj) Reset()                    { *m = MediaObj{} }
func (m *MediaObj) String() string            { return proto1.CompactTextString(m) }
func (*MediaObj) ProtoMessage()               {}
func (*MediaObj) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MediaObj) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

func (m *MediaObj) GetVideoSrc() string {
	if m != nil {
		return m.VideoSrc
	}
	return ""
}

func (m *MediaObj) GetVideoHtmlUrl() string {
	if m != nil {
		return m.VideoHtmlUrl
	}
	return ""
}

func (m *MediaObj) GetOtherData() map[string]*google_protobuf.Any {
	if m != nil {
		return m.OtherData
	}
	return nil
}

func init() {
	proto1.RegisterType((*ArticleObj)(nil), "proto.ArticleObj")
	proto1.RegisterType((*UserObj)(nil), "proto.UserObj")
	proto1.RegisterType((*MediaObj)(nil), "proto.MediaObj")
}

func init() { proto1.RegisterFile("proto/crawler.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 561 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0x41, 0x8f, 0xd2, 0x40,
	0x18, 0x4d, 0x97, 0xed, 0x02, 0x1f, 0x2b, 0x9a, 0x11, 0x75, 0x24, 0x4a, 0x1a, 0xa2, 0x1b, 0xe2,
	0xa1, 0x24, 0x78, 0x31, 0x6a, 0x4c, 0x36, 0xab, 0x89, 0x1e, 0x5c, 0x4c, 0x59, 0x7e, 0xc0, 0xb4,
	0xfd, 0x5c, 0xba, 0xb4, 0x1d, 0x33, 0x4c, 0xd7, 0xf0, 0x0b, 0xfd, 0x43, 0x1e, 0x3c, 0x9a, 0xf9,
	0xa6, 0x05, 0x0a, 0x17, 0xbd, 0xec, 0x89, 0x79, 0xef, 0x4d, 0xbf, 0xce, 0x7b, 0x7d, 0x03, 0x3c,
	0xfc, 0xa1, 0xa4, 0x96, 0xe3, 0x48, 0x89, 0x9f, 0x29, 0x2a, 0x9f, 0x10, 0x73, 0xe9, 0xa7, 0xff,
	0xf4, 0x5a, 0xca, 0xeb, 0x14, 0xc7, 0x84, 0xc2, 0xe2, 0xfb, 0x58, 0xe4, 0x6b, 0xbb, 0x63, 0xf8,
	0xcb, 0x05, 0x38, 0x57, 0x3a, 0x89, 0x52, 0x9c, 0x86, 0x37, 0x8c, 0xc1, 0x71, 0x1c, 0x26, 0x31,
	0x77, 0x3c, 0x67, 0xc4, 0x02, 0x5a, 0xb3, 0x3e, 0xb4, 0x56, 0xb2, 0x50, 0x11, 0x7e, 0x89, 0xf9,
	0x91, 0xe7, 0x8c, 0xda, 0xc1, 0x06, 0xb3, 0x1e, 0xb8, 0x3a, 0xd1, 0x29, 0xf2, 0x06, 0x09, 0x16,
	0x30, 0x0f, 0x3a, 0x91, 0xcc, 0x35, 0xe6, 0xfa, 0xb3, 0xce, 0x52, 0x7e, 0x4c, 0xda, 0x2e, 0xc5,
	0xce, 0xe0, 0x44, 0x14, 0x7a, 0x21, 0x15, 0x77, 0x3d, 0x67, 0xd4, 0x99, 0x74, 0xed, 0x71, 0xfc,
	0xf9, 0x0a, 0xd5, 0x34, 0xbc, 0x09, 0x4a, 0x95, 0x9d, 0x41, 0xd7, 0xbe, 0x6b, 0x96, 0x68, 0xbc,
	0x14, 0x19, 0xf2, 0x13, 0x1a, 0xb6, 0xc7, 0xb2, 0x21, 0x9c, 0xce, 0x88, 0xf9, 0x56, 0x84, 0xf3,
	0xab, 0x0b, 0xde, 0xa4, 0xf3, 0xd7, 0x38, 0xf6, 0x02, 0xee, 0x6d, 0xf0, 0x55, 0x92, 0x21, 0x6f,
	0xd1, 0xa8, 0x3a, 0xc9, 0x9e, 0x41, 0xdb, 0xce, 0x9e, 0xab, 0x94, 0xb7, 0x69, 0xc7, 0x96, 0x30,
	0x33, 0xf4, 0xa2, 0xc8, 0xc2, 0x5c, 0x24, 0xe9, 0xca, 0xec, 0x00, 0xaf, 0x61, 0x66, 0xd4, 0x48,
	0xf6, 0x12, 0xdc, 0x0c, 0xe3, 0x44, 0xf0, 0x0e, 0x99, 0xbb, 0x5f, 0x9a, 0xfb, 0x6a, 0x38, 0xe3,
	0xce, 0xaa, 0x75, 0x73, 0x17, 0x32, 0x46, 0x7e, 0xba, 0x6f, 0xce, 0xb0, 0x8c, 0x43, 0x33, 0x4d,
	0x96, 0x78, 0x59, 0x64, 0xbc, 0x47, 0xbe, 0x2a, 0xc8, 0x06, 0x00, 0x91, 0xcc, 0x32, 0xcc, 0xb5,
	0x11, 0x1f, 0x91, 0xb8, 0xc3, 0x98, 0x27, 0x15, 0x8a, 0xd8, 0x88, 0x8f, 0xed, 0x93, 0x25, 0x34,
	0x36, 0x23, 0x85, 0x42, 0xa3, 0x49, 0xeb, 0x09, 0x69, 0x5b, 0x82, 0xe6, 0x12, 0xa0, 0x9c, 0x38,
	0x9d, 0x6a, 0x87, 0x61, 0x1f, 0xa0, 0x2d, 0xf5, 0x02, 0xd5, 0x47, 0xa1, 0x05, 0x1f, 0x78, 0x8d,
	0x51, 0x67, 0xe2, 0x95, 0x26, 0xb7, 0x65, 0xf2, 0xa7, 0xd5, 0x96, 0x4f, 0xb9, 0x56, 0xeb, 0x60,
	0xfb, 0x48, 0x3f, 0x80, 0x6e, 0x5d, 0x64, 0x0f, 0xa0, 0xb1, 0xc4, 0x35, 0xf5, 0xae, 0x1d, 0x98,
	0x25, 0x7b, 0x05, 0xee, 0xad, 0x48, 0x0b, 0xa4, 0xce, 0x75, 0x26, 0x3d, 0xdf, 0x96, 0xd8, 0xaf,
	0x4a, 0xec, 0x9f, 0xe7, 0xeb, 0xc0, 0x6e, 0x79, 0x7b, 0xf4, 0xc6, 0x19, 0xfe, 0x3e, 0x82, 0x66,
	0x59, 0x9f, 0xff, 0xae, 0x71, 0x1f, 0x5a, 0x79, 0x12, 0x2d, 0x73, 0x53, 0x30, 0xdb, 0xe4, 0x0d,
	0x36, 0x19, 0x26, 0x91, 0xcc, 0xcd, 0xc7, 0xb6, 0x45, 0xae, 0xa0, 0x49, 0x49, 0x44, 0x91, 0x2c,
	0x6c, 0xfa, 0xae, 0x4d, 0x69, 0xcb, 0xfc, 0x73, 0x79, 0x39, 0x34, 0x17, 0x32, 0xa3, 0xc2, 0x35,
	0xed, 0x1b, 0x4a, 0x68, 0x52, 0x89, 0x71, 0x55, 0x16, 0xd5, 0x2c, 0xd9, 0xbb, 0xc3, 0xe4, 0x9f,
	0xd7, 0xef, 0xce, 0x1d, 0xc7, 0xfe, 0xc7, 0x81, 0x56, 0x55, 0xec, 0x5a, 0xc6, 0xce, 0x61, 0xc6,
	0xb7, 0x49, 0x8c, 0x72, 0xa6, 0xa2, 0x2a, 0xff, 0x0a, 0x9b, 0xeb, 0x4b, 0x6b, 0xf3, 0xdf, 0x60,
	0x62, 0xb0, 0xdf, 0xa0, 0xc6, 0xb1, 0xf7, 0x87, 0xce, 0x07, 0x7b, 0x17, 0xeb, 0x6e, 0xad, 0x87,
	0x27, 0x24, 0xbc, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x05, 0xdf, 0x58, 0xff, 0x7b, 0x05, 0x00,
	0x00,
}
